symfony/monolog-bundle

DependencyInjection/Compiler/DebugHandlerPass.php
When running CLI commands with the `--no-debug` option in the dev environment, the DebugHandler was still being registered. For long running commands with lots of logging (I like to use -vvv) this will cause memory issues.
The DebugCompilerPass now checks the `kernel.debug` parameter, suggested by @fabpot in #37.
=> Add check to kernel.debug in DebugCompilerPass

Resources/config/monolog.xml
Logstash formatter needs a first argument (applicationName) in order to works correctly 
Reference: https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/LogstashFormatter.php#L58
PR related: https://github.com/symfony/MonologBundle/commit/5b647df5d824488e1c3c7bede470757756df1afb
=> Fix Logstash formatter issue

Resources/doc/index.rst
Added installation chapter.
Easy picks on bundle side from symfony/symfony-docs#4983
=> moving MonologBundle docs to bundle repo

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
This PR extends the hipchat handler configuration to allow the setting of different message_format (https://www.hipchat.com/docs/api/method/rooms/message) and the use of an ssl connection.
Both options are available in the constructor of the HipchatHandler (https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/HipChatHandler.php#L81) but were not configurable yet.
Please bear with me. This is my first Symfony related PR.
=> Extend hipchat handler configuration to allow message_format config

.travis.yml
At the moment `.travis.yml` [is broken](http://lint.travis-ci.org/symfony/MonologBundle):
1. `php:` key is missing
2. `then` is missing in a bash command
=> Fixed travis-ci

DependencyInjection/Compiler/LoggerChannelPass.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/Fixtures/xml/parameterized_handlers.xml, Tests/DependencyInjection/Fixtures/yml/parameterized_handlers.yml
It's a PR for #122
Now it's possible to specify channel as a parameter in a tagged configuration:
XML:
<services>
<service id="foo_logger" class="Foo">
<tag name="monolog.logger" channel="%channel_parameter%" />
</service>
</services>
YML:
services:
foo_logger:
class: Foo
tags: [{ name: monolog.logger, channel: %channel_parameter% }]
=> Added resolving channel name via container parameters

DependencyInjection/Compiler/AddSwiftMailerTransportPass.php
The transport of the default mailer was always used, even if the monolog handler
has a different mailer setting. When using a non-default mailer, the correct transport
was never called and the monolog emails never sent.
Instead of assuming the default mailer transport, I now set the transport of the used
mailer.
Fixes #137.
=> Default swiftmailer transport was always used

DependencyInjection/MonologExtension.php, SwiftMailer/MessageFactory.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php
Hiya guys!
Blackfire comparison: https://blackfire.io/profiles/compare/0ab8c333-3272-4af0-8b57-ff0b4e3478de/graph
Prior to this, in order for the main logger to be instantiated, if you had a swiftmailer handler, ultimately a single Swift_Message would be created, even if you didn't need it. That sounds minor, but due to Swift's
autoloading, it required quite a few extra classes, which added a small amount of extra memory (~1MB) and extra CPU due to the auto-loader (~10-20ms).
This keeps BC, only renaming a service that was private anyways.
Cheers!
=> Adding a Swift MessageFactory for performance

DependencyInjection/Compiler/AddSwiftMailerTransportPass.php
This [commit](https://github.com/symfony/monolog-bundle/commit/159129fd3d15e37c49756f71c3204b56860026bc) introduced a BC break. 
The suggested configuration from the [Symfony docs](http://symfony.com/doc/current/cookbook/logging/monolog_email.html) look like this: 
```yaml
monolog:
handlers:
mail:
type:         fingers_crossed
action_level: critical
handler:      buffered
buffered:
type:    buffer
handler: swift
swift:
type:       swift_mailer
from_email: error@example.com
to_email:   error@example.com
subject:    An Error Occurred!
level:      debug
```
The value of the handers['swift']['mailer'] will be default to 'mailer'. This is okey because the SwiftBundle has an alias for 'mailer'. (`$container->setAlias('mailer', 'swiftmailer.mailer');`).
When we use the 'mailer' in our …
=> Fixed BC break in AdDSwiftMailerTransportPass

DependencyInjection/Compiler/LoggerChannelPass.php
As @Tobion pointed out in a comment to my merged PR #138, the `LoggerChannelPass` still triggers deprecation warnings with Symfony 2.8. When writing my patch, I was not aware that I could suppress the warning by passing `false` as parameter to `Reference::isStrict()`.
I think, suppressing the warning is the way to go because we already took care of the deprecation in #138: Once `isStrict()` is gone, it won't be called anymore. But as long as it's still there, other bundles might be using that functionality, so imho there's no way around calling `isStrict()` without potentially breaking stuff.
=> Don't trigger a deprecation warning for Reference::isStrict()

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/ConfigurationTest.php
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #144
| License       | n/a
The `ignore_error` option was missing in the Bundle's `Configuration.php`
=> Added missing ignore_error option to Configuration

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Resources/config/schema/monolog-1.0.xsd
There are two currently unexposed parameters of the [`HipChatHandler`](https://github.com/Seldaek/monolog/blob/f86e643a5814f90724ddd09b99304611633f92e0/src/Monolog/Handler/HipChatHandler.php#L98): 
* `$host` which is required to support [HipChat Server](https://www.hipchat.com/server)
* `$version` the API version, where you might want to switch to the v2 api
These two options are currently not exposed in the configuration.
I wasn't sure on how to add these options and especially unsure about how to define a fallback in the configuration, if the option is used by multiple handlers (like `host`). The current way is to just pass `null` in these parameters and set the defaults in the handler directly:
```php
public function __construct($token, $room, $name = 'Monolog', $notify = false, $level …
```
=> Expose all of HipChat's parameters

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Resources/config/schema/monolog-1.0.xsd
Hi,
Just add the possibility to authenticate against a protected Elasticsearch server.
Also allow to connect to Elasticsearch server behind SSL.
First pull request here, let me know if something's wrong ;)
=> Allow authentication against protected Elasticsearch server

DependencyInjection/MonologExtension.php
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a
Related to symfony/symfony#16464. cc @weaverryan
=> Allow to autowire the default logger

DependencyInjection/Configuration.php
With default elasticksearch handler transport I have exception on linux machine: 'Invalid transport'.
In elastica client liblary default transport value is 'Http' not 'http'.
https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Connection.php#L29
https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Transport/AbstractTransport.php#L92
=> Default elasticsearch handler transport uppercase first character

DependencyInjection/Configuration.php
Add a small notice to the slack configuration that the channel name have to contain the '#'.
=> Improve Documentation

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, MonologBundle.php, composer.json
Fixes https://github.com/symfony/symfony/pull/17168
Allows people to add stacktraces to their log when they want to.
=> Add include_stacktraces configuration option to handlers

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |
=> Add timeout and conection timeout to logentries handler config definition

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
This will also serve as future reference for adding additional Raven Client params.
=> Add `auto_log_stacks` param support for Sentry (Raven Client)

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/MonologExtensionTest.php
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 
Marked nested handlers with not be pushed to the logger handler array.
This options may be usefull when using custom handler (as service type handlers) which rely on a sub handler defined in the monolog-bundle configuration.
Marking this subhandler as nested avoid monolog to directly call it.
```yaml
monolog:
handlers:
foo:
type: service
id: my_site.custom_log_handler
bar:
type:  stream
path:  "%kernel.logs_dir%/%kernel.environment%-bar.log"
level: debug
nested: true
services:
my_site.custom_log_handler:
class: AppBundle\Logger\CustomHandler
arguments:
- "@monolog.handler.bar"
```
=> Add a nested option on handler config definition

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Resources/config/schema/monolog-1.0.xsd
Add app_name option for New Relic handler.
=> Allow to initialise New Relic app_name

composer.json
The `useMicrosecondTimestamps()` method was introduced in Monolog
1.18.0.
=> bump Monolog versions

Resources/config/schema/monolog-1.0.xsd
content-type is missing from the XSD. making it impossible to use the swift_mailer handler to send HTML formatted emails with XML config
=> Added content-type to schema

DependencyInjection/MonologExtension.php
As you can see in [the source code of the PHP uniqid() function](https://github.com/php/php-src/blob/1c295d4a9ac78fcc2f77d6695987598bb7abcb83/ext/standard/uniqid.c#L68) when you don't pass `true` as the second argument, PHP sleeps the application for 1 microsecond (`usleep(1)`)
Symfony uses `true` almost everywhere, but this bundle still had some uniqid() calls without this option.
=> Use "more entropy" option when using uniqid() function

DependencyInjection/Compiler/DebugHandlerPass.php, DependencyInjection/MonologExtension.php, MonologBundle.php, Tests/DependencyInjection/Fixtures/yml/parameterized_handlers.yml
Related to https://github.com/symfony/symfony/pull/20416
=> Deprecate DebugHandlerPass in favor of AddDebugLogProcessorPass in FrameworkBundle

DependencyInjection/Compiler/DebugHandlerPass.php
As the cache is shared between the different server APIs, the debug handler needs to take care of abstaining itself.
After symfony/symfony#21061 being merged, the changes made in fbbcefd7821edfaa31a48712bba0960979243c1c should no longer be necessary.
=> revert disabling DebugHandler in CLI environments

DependencyInjection/Compiler/DebugHandlerPass.php, DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, MonologBundle.php, Tests/DependencyInjection/MonologExtensionTest.php
This reverts commit b46da89f264efa7ed42ed3db6b9b69a2b2ef2163.
The class is necessary to support Symfony <3.2. Closes #190.
The 3.x version of the bundle contains only 2 changes compared to 2.11:
- breaking support for Symfony <3.2 (while still announcing compatibility), which is what got reverted here
- adding support for a new Monolog feature (which could totally fit in 2.x btw).
As we still need to keep support for the Symfony LTS, and the 3.x series is currently broken for us, I'm suggesting here to revert the removal (effectively making it a follow-up of 2.x, which would allow to avoid maintaining 2 branches).
The other alternative would be to kill the existing 3.x releases entirely to forbid them to be installed in a Symfony 2.8 project allowing ``symfony/monolog-bundle: ^2.8 || …
=> Revert "Drop DebugHandlerPass"

DependencyInjection/Compiler/DebugHandlerPass.php, MonologBundle.php
We should not trigger the deprecation when using a Symfony version not using the new feature
=> Add a better detection of the deprecation case

DependencyInjection/Configuration.php, Tests/DependencyInjection/ConfigurationTest.php
VERBOSITY_QUIET is set to ERROR by default and you can't override that, even though the OutputInterface allows to use this verbosity. In the default configuration, quiet doesn't mean really quiet as errors are still logged.
=> Allow to override VERBOSITY_QUIET in configuration

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
Slackbot handler does not work, because there is grammar mistake and curl can not handle # sign from channel name.
=> bug  #208 Slackbot handler does not work

DependencyInjection/Configuration.php
ref https://github.com/symfony/monolog-bundle/issues/223
PHP 7.2+ issues a warning when trying to count a non Iterable. The case in this code is not clear if it should just check for the presence of a handler or not. I suspect the original intention was to make sure the specified handler is defined in the configuration, but this should happen in the Extension?
=> Fix invalid use of count() in PHP 7.2

README.md
Not affecting any supported Symfony versions, and even downright wrong since major version 3 was released.
=> Remove obsolete warnings in README

.travis.yml
* do not use dev dependencies for the Symfony 2.8 job
* add a job for Symfony 3.4
* use PHP 7.1 for the job using dev dependencies
* install the PhpUnitBridge dependencies during the "install" step
=> update the Travis CI config

.travis.yml, Tests/DependencyInjection/Compiler/AddProcessorsPassTest.php, Tests/DependencyInjection/Compiler/AddSwiftMailerTransportPassTest.php, Tests/DependencyInjection/Compiler/FixEmptyLoggerPassTest.php, Tests/DependencyInjection/Compiler/LoggerChannelPassTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/DependencyInjectionTest.php
This PR switches the PHPUnit test base class from PEAR-style `PHPUnit_Framework_TestCase` to the namespaced `PHPUnit\Framework\TestCase`, which enables us to run the tests with PHPUnit 6 as well.
=> Switch to namespaced PHPUnit classes

Tests/DependencyInjection/FixtureMonologExtensionTest.php
Tests were not doing the right assertions, and so not covering the feature.
This was detected by looking at why PHPUnit was marking the test as risky.
=> Clean tests about the PSR-3 processor

DependencyInjection/Compiler/LoggerChannelPass.php
Channels can be created for 2 reasons:
- because a service requests to use it through the monolog.logger tag, in which case a private channel is fine (as it is injected using the DIC)
- because the bundle config asks to create it. In this case, the channel should be a public service, as the use case is to be able to use this channel through public access (otherwise, the previous way would have been used).
This is an improved versions over #247 as only channels created through config become public in Symfony 4.
/cc @derrabus
=> Enforce that channels defined in the config are public loggers

DependencyInjection/Compiler/LoggerChannelPass.php, Tests/DependencyInjection/Compiler/LoggerChannelPassTest.php
This only works on Symfony 3.4+, not on Symfony 3.3, but 3.3 is EOL already so this is fine.
Closes #218 
Closes #228
Replaces #251
=> Make channel selection work with autowired arguments

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Resources/config/schema/monolog-1.0.xsd, Tests/DependencyInjection/MonologExtensionTest.php
Dependent upon https://github.com/symfony/symfony/pull/23707
This PR introduces configuration to integrate a new `HttpCodeActivationStrategy`, offering an easy way to ignore specific HTTP status codes.
=> Add configuration for new HttpCodeActivationStrategy

DependencyInjection/Compiler/LoggerChannelPass.php, Tests/DependencyInjection/Compiler/LoggerChannelPassTest.php, composer.json
This depends on https://github.com/symfony/symfony/pull/27271, hence the new min version of the DI component
=> Fix the autowiring of the channel logger in autoconfigured services

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php
Currently, logs are processed twice or more. But only leaf handlers should process them by default.
=> Disable process_psr_3_messages for non-leaf handlers

DependencyInjection/MonologExtension.php, Tests/DependencyInjection/MonologExtensionTest.php
Due to the early handling of `service` handlers in the extension, a service handler can't be marked as nested using the `nested` configuration option. This can cause issues when declaring multiple (nested) handlers of which one is then chosen based on the environment: since the service handler can't explicitly be marked as nested, it will always pushed to the logger even when it shouldn't be used.
=> Allow marking service handlers as nested

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
Like that we will be able to use this configuration (for example):
```yaml
console:
type: console
process_psr_3_messages: false
channels: ["!event", "!doctrine", "!console"]
console_formater_options:
format: "%%datetime%% %%start_tag%%%%level_name%%%%end_tag%% <comment>[%%channel%%]</> %%message%%%%context%%\n"
multiline: false
```
see also https://github.com/symfony/symfony/pull/30345
=> Expose configuration for the ConsoleHandler

DependencyInjection/MonologExtension.php
Replaces https://github.com/symfony/symfony/pull/27801 (which has been reverted meanwhile)
Leverages https://github.com/Seldaek/monolog/pull/1204
Already documented in https://github.com/symfony/symfony-docs/pull/9996 (but doc needs update)
=> Register processors for autoconfiguration

DependencyInjection/Configuration.php
As the `DeduplicationHandler` extends the `BufferHandler` I think the wording for the `handler` parameter should be the same.
=> Fix typo in PhpDoc

.travis.yml, CHANGELOG.md, DependencyInjection/Compiler/LoggerChannelPass.php, DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, LICENSE, Tests/DependencyInjection/Compiler/LoggerChannelPassTest.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/MonologExtensionTest.php, composer.json
Fixes https://github.com/php-pm/php-pm-httpkernel/issues/134 and https://github.com/php-pm/php-pm-httpkernel/issues/62
When using [PHP-PM](https://github.com/php-pm/php-pm) the worker does not die at the end of the request, so the shutdown functions registered by monolog are never triggered (so for example `BufferHandler` never flushes). This PR partially fixes the problem by flushing the loggers containing a `flush` function at the end of each request.
I did not use the `close` function (mentioned in https://github.com/Seldaek/monolog/issues/1053) because some loggers use sockets or other connections that would be closed in this case and not be reusable in the next request.
I'm not sure if this is the best solution to this problem, happy to discuss alternatives if there is a better way.
=> Flush loggers on kernel.reset

CHANGELOG.md, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/MonologExtensionTest.php
replaces #275
fixed https://github.com/symfony/symfony/issues/26969
I have fixed confliects + CS + updated the CHANGELOG
=> Deprecate "excluded_404s" option

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
In sentry 9, we can filter logs thourgh environments. This PR allows to support this option.
=> Support environment option for raven client

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
As outlined in ticket #266:
The SyslogUdpHandler constructor has a sixth parameter "ident", defaulting to "php".
However, the current Monolog Bundle implementation allows setting only the first five. Which defaults to the "ident" being set to "php".
In our case, we are using papertrail as a log backend, and use the same webserver for multiple small projects. In papertrail, that results in the following output:
```
May 05 02:16:30 vagrant php:  app.ERROR: fooo {"exception":"[object] (Exception(code: 0): fooo at /var/customers/webs/fastbolt/https/env1.fastbolt.com/src/Pricecalc/UserBundle/Controller/SecurityController.php:36)","username":"anon.","uri":"http://env1.dev.local/login","level":"critical"} []
May 05 02:18:32 vagrant php:  app.ERROR: fooo {"exception":"[object] (Exception(code: …
```
=> Allow setting "ident" parameter for SyslogUdpHandler, affects #266

CHANGELOG.md, DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Resources/config/schema/monolog-1.0.xsd, Tests/DependencyInjection/ConfigurationTest.php
fixed https://github.com/symfony/monolog-bundle/pull/292
=> Added support for Redis configuration

DependencyInjection/Configuration.php
Related to #296 
Elasticsearch host must not have (http://) or (https://) in the configuration, just the IP or the domain name.
Otherwise an error is thrown that there is `No enabled connection`
=> Update Configuration Documentation for Elasticsearch

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Resources/config/schema/monolog-1.0.xsd, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/Fixtures/xml/native_mailer.xml, Tests/DependencyInjection/Fixtures/yml/native_mailer.yml
The native mailer is able to have additional headers, but it
wasn't possible to give it any headers in the configuration.
Swift mailer may have a content_type key but not native mailer.
A new "headers" key is now allowed in the handler configuration, so a
list of headers may be given to the handler. Only native mailer supports
it.
Related to #272
=> Add support for headers in native mailer

CHANGELOG.md, DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/MonologExtensionTest.php
As said on #310, sentry completely changed their API and even stopped calling their client "raven", using now php-http to handle the requests to their api.
So this PR adds a new type in the config to support the handler they made.
I'm not sure on a few points (such as the self-referencing hub, which I commented because otherwise it would go on an infinite recursion problem), and I based the service definition on [sentry's bundle](https://github.com/getsentry/sentry-symfony).
Poke @Jean85 maybe, as he is maintaining (as far as I can tell ?) the current sentry bundle.
Fixes #310
=> #310 : Add sentry 2.0 type

DependencyInjection/Compiler/AddProcessorsPass.php, DependencyInjection/Compiler/AddSwiftMailerTransportPass.php, DependencyInjection/Compiler/DebugHandlerPass.php, DependencyInjection/Compiler/FixEmptyLoggerPass.php, DependencyInjection/Compiler/LoggerChannelPass.php, DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/Compiler/AddProcessorsPassTest.php, Tests/DependencyInjection/Compiler/AddSwiftMailerTransportPassTest.php, Tests/DependencyInjection/Compiler/FixEmptyLoggerPassTest.php, Tests/DependencyInjection/Compiler/LoggerChannelPassTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/MonologExtensionTest.php
Since the minimum version was bumped last year to 5.6 we should leverage some of the niceties that we have.
=> Use short array syntax

CHANGELOG.md, DependencyInjection/Compiler/LoggerChannelPass.php, Tests/DependencyInjection/Compiler/LoggerChannelPassTest.php
resolved #278
- Added possibility for auto-wire monolog channels according to variable type-hint and name.
Variable will have appropriated name to camel cased monolog channel service name: `monolog.logger.acme -> $acmeLogger`.
- Removed useless import `DefinitionDecorator`.
- Renamed additional channel in the tests from `manualchan` to `additional`
=> Symfony autowiring monolog channels #278

DependencyInjection/MonologExtension.php, Tests/DependencyInjection/MonologExtensionTest.php
This would allow the wiring up of v2 handlers and preventing wiring of removed on V2 API.
Wanted to get feedback if this approach is suitable before I continue with adding tests to cover the validation aspect.
If you like the approach this is taking do you have any guidelines around testing against multiple versions of monolog? e.g. something like this https://github.com/g1a/composer-test-scenarios
Release notes: https://github.com/Seldaek/monolog/releases/tag/2.0.0
=> Supporting v2 handlers and removing removed.

.travis.yml, Tests/DependencyInjection/Compiler/AddSwiftMailerTransportPassTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/Fixtures/yml/multiple_handlers.yml, Tests/DependencyInjection/MonologExtensionTest.php, Tests/DependencyInjection/XmlMonologExtensionTest.php, Tests/DependencyInjection/YamlMonologExtensionTest.php, composer.json
Combines previous PRs #358 and #359 together with fixes for failing tests on Travis.
* Updates travis test matrix:
* Adds PHP 7.4 to test matrix
* Expands test matrix for PHP 7.2+ to check against both monolog 1 & 2
* Fixes PHPUnit deprecations:
* Fixes invalid method signature for `setUp()`
* Replaces deprecated assertions (assertContains, assertNotContains)
* Replaces deprecated expectedExceptions annotations
* Fixes missing service definitions in container configurations
Closes #351 as well
=> Fix tests for php7

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
Add support for the new symfony mailer directly on the bundle after the MailerHandle was added to the bridge on https://github.com/symfony/symfony/pull/33456
Also this can make https://github.com/symfony/symfony-docs/issues/13077 move forward
Tests are failing due to incompatible phpunit versions, not sure how to fix this...
=> Add Symfony Mailer support

CHANGELOG.md, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/MonologExtensionTest.php
=> Autoconfigure resettable processors with the kernel.reset tag

DependencyInjection/MonologExtension.php, Tests/DependencyInjection/MonologExtensionTest.php
While converting the logLevel into the right const value, calling `$container->resolveEnvPlaceholders($level, true);` does not always throw an exception and returns the value provided in INPUT, leading to an infinite loop
This PR fixes  https://github.com/symfony/monolog-bundle/issues/367#issuecomment-723988352 BUT is not related to the issue https://github.com/symfony/monolog-bundle/issues/367#issue-718712384
=> Fix infinite loop in LogLevel detection

.travis.yml
In order to fix failing PHP 7.3 tests:
`PHP Fatal error:  Uncaught SebastianBergmann\CodeCoverage\RuntimeException: XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set in /home/travis/build/symfony/monolog-bundle/.phpunit/phpunit-8.3-0/vendor/phpunit/php-code-coverage/src/Driver/Xdebug.php:50`
Travis builds are failing under the new version of xdebug, you can fix that with setting XDEBUG_MODE to "coverage" in the config. See https://travis-ci.community/t/xdebug-3-is-installed-by-default-breaking-builds/10748
=> Fix travis xdebug coverage

DependencyInjection/Compiler/AddProcessorsPass.php, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/Compiler/AddProcessorsPassTest.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/Fixtures/xml/process_psr_3_messages_null.xml, Tests/DependencyInjection/Fixtures/yml/process_psr_3_messages_null.yml
This PR fixes call to undefined method `pushProcessor` on handler that does not implements the `ProcessableHandlerInterface`.
=> Fix call to handler::pushProcessor

CHANGELOG.md, DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
This PR adds the support of Datadog to the list of supported integrations.
⚠️ We need to wait for this related `monolog` PR to be merged first: https://github.com/Seldaek/monolog/pull/1504 ⚠️
The configuration looks like this (example):
```yml
monolog:
handlers:
datadog:
type: datadog
region: eu
token: xxxxxxxxxxxxxxxxxxxxx
app_name: foo
```
Here's what is outputed in the datadog log section:
=> Add Datadog monolog integration

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/ConfigurationTest.php
The `console_formater_options` has a typo. This PR deprecates the option and replaces it with `console_formatter_options` while maintaining backwards compatibility.
=> Typo in console formatter option name

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Resources/config/schema/monolog-1.0.xsd, Tests/DependencyInjection/MonologExtensionTest.php
As mentioned in https://github.com/getsentry/sentry-docs/pull/3137#discussion_r588942726 , this will allow users to set a custom hub service, eg the one registered by the [Sentry bundle](https://github.com/getsentry/sentry-symfony).
=> Add ability to specify custom Sentry hub service

DependencyInjection/MonologExtension.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/Fixtures/xml/handlers.xml, Tests/DependencyInjection/Fixtures/yml/handlers.yml
This PR removes the invalid handlers added in #321: Adding an handler is not only about adding the mapping `shortName` <=> `class`: The constructor's arguments have to be defined in the `buildHandler` function. Otherwise, we get the following exception:
```
InvalidArgumentException: Invalid handler type "logmatic" given for handler "logmatic"
/data/oss/monolog-bundle/DependencyInjection/MonologExtension.php:911
```
This PR adds support for handler "noop". 
Re-adding supports for the other (more complex) handlers could be done in dedicated PR.
=> Remove invalid handlers

DependencyInjection/MonologExtension.php, Tests/DependencyInjection/MonologExtensionTest.php
Fixing Symfony issue with different Hub's while decorating default Sentry handler for extended event context.
Common way to extend log event context is to decorate Sentry\Monolog\Handler:
```php
final class SentryContextHandlerDecorator extends AbstractProcessingHandler
{
private Handler $handler;
public function __construct(Handler $handler)
{
$this->handler = $handler;
parent::__construct($handler->getLevel(), $handler->getBubble());
}
public function handle(array $record): bool
{
$result = false;
withScope(function (Scope $scope) use ($record, &$result): void {
if (isset($record['context']) && is_array($record['context']) && count($record['context']) > 0) {
$scope->setContext('context', $record['context']);
}
$result = $this->handler->handle($record);
});
return $result;
}
}
```
But if …
=> Add Sentry Hub instance in DI container to resolve event context issue

DependencyInjection/Configuration.php
For better readability and to fix https://github.com/symfony/monolog-bundle/issues/412
As proposed here https://github.com/symfony/monolog-bundle/issues/412#issuecomment-1091780515
Workarround for PHP issue php/php-src#8315
=> Split configuration

DependencyInjection/Configuration.php
The fallbackgroup is already supported but wasn't listed in the configuration documentation.
=> Add fallbackgroup handler to configuration documentation

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/MonologExtensionTest.php
Due to updates in sentry php library which allowing to fill extra context data in [3.4.0](https://github.com/getsentry/sentry-php/blob/master/CHANGELOG.md#340-2022-03-14) added corresponding flag for handler.
=> Add flag for filling sentry extra context

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Resources/config/schema/monolog-1.0.xsd, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/Fixtures/xml/process_psr_3_messages_with_arguments.xml, Tests/DependencyInjection/Fixtures/xml/process_psr_3_messages_without_arguments.xml, Tests/DependencyInjection/Fixtures/yml/process_psr_3_messages_with_arguments.yml, Tests/DependencyInjection/Fixtures/yml/process_psr_3_messages_without_arguments.yml
Adds the ability to configure the PsrLogMessageProcessor using semantic configuration.
See https://github.com/Seldaek/monolog/pull/940, https://github.com/Seldaek/monolog/pull/1046, https://github.com/Seldaek/monolog/pull/1487.
=> Add ability to configure the PsrLogMessageProcessor

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
=> Deprecate elasticsearch type, and split it into elastica and elastic_search types

DependencyInjection/MonologExtension.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/MonologExtensionTest.php
Resolves #413, #444
Currently, the log level is read when the container built. This means we cannot change a log level at runtime using env vars.
With this change, log level can be modified for a specific command run: `LOG_LEVEL=debug bin/console ...`
~I would like to get some feedbacks before updating tests. I don't know yet what is the best strategy to check the resolution of the values.~
=> Resolve "level" env var at runtime

Tests/DependencyInjection/Fixtures/AsMonologProcessor/FooProcessorWithPriority.php, Tests/DependencyInjection/MonologExtensionTest.php
This PR contains two small fixes for the Monolog processor autoconfiguration test. The test currently fails because of changes in https://github.com/Seldaek/monolog/pull/1797.
Not sure if I should provide more information. Please let me know if I missed something 🙂
=> Fix test for autoconfiguration

.github/workflows/ci.yaml, DependencyInjection/Compiler/LoggerChannelPass.php, DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, MonologBundle.php, Tests/DependencyInjection/Compiler/LoggerChannelPassTest.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/MonologExtensionTest.php, composer.json
This PR drops support for Symfony 4 and unmaintained Symfony 5 branches. This allows us to throw out obsolete compatibility code for unmaintained Symfony releases.
=> Drop Support for Symfony 4

CHANGELOG.md
Those entries were not provided in the PRs doing the changes.
=> Add changelog entries for unreleased changes

CHANGELOG.md, DependencyInjection/Compiler/AddProcessorsPass.php, DependencyInjection/Compiler/AddSwiftMailerTransportPass.php, DependencyInjection/Compiler/FixEmptyLoggerPass.php, DependencyInjection/Compiler/LoggerChannelPass.php, DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, MonologBundle.php
This will allow us to have a clearer BC API for our future versions.
=> Tag classes as final or internal based on their usages

CHANGELOG.md, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/Fixtures/ServiceWithChannel.php, Tests/DependencyInjection/MonologExtensionTest.php
Configuring custom channels on some services is one of the last reasons I have for defining services explicitly in my config files. This attribute allows to solve that.
=> Add support for the `#[WithMonologChannel]` attribute of Monolog 3.5 to autoconfigure the channel

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
Figured out the SamplingHandler was never added to the configuration, as per #4 to-do list :)
=> Add configuration support for SamplingHandler

Tests/DependencyInjection/ConfigurationTest.php
Following https://github.com/symfony/symfony/pull/58490#issuecomment-2453496578. Until the Symfony PR, null wasn't supported in boolean nodes and defaulted to true.
=> Fix test with `symfony/config:^7.2`

Tests/DependencyInjection/Compiler/AddSwiftMailerTransportPassTest.php
see https://github.com/symfony/monolog-bundle/pull/493#discussion_r1830879914
=> do not mock Symfony DI component classes

Tests/DependencyInjection/Compiler/AddSwiftMailerTransportPassTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/DependencyInjectionTestCase.php, Tests/DependencyInjection/FixtureMonologExtensionTestCase.php, Tests/DependencyInjection/MonologExtensionTest.php, Tests/DependencyInjection/XmlMonologExtensionTest.php, Tests/DependencyInjection/YamlMonologExtensionTest.php
This PR fixes a couple of compatibility issues with PHPUnit 11:
* Data provider methods must be static.
* The mock builder does not have a `setMethods()` method anymore.
* Abstract test classes must not use the suffix `Test`.
Note: The tests are still run with PHPUnit 8.5 and 9.6 though. The PR merely enables us to use PHPUnit 11 in the future.
=> Fix compatibility with PHPUnit 11
