Resources/config/monolog.xml
Add missing Logstash formatter
=> Add Logstash Formatter to monolog.xml

DependencyInjection/MonologExtension.php
as reported in http://fabbot.io/report/symfony/MonologBundle/127/f7d8053fb3afca73b8d3fb5b1c1c759cd2f4a9ce
=> fix code style

.travis.yml
* use container based infrastructure
* add PHP 7 build job
* cache Composer cache directory on Travis
* report build status as fast as possible
* add build with lowest possible dependency versions
* run tests with different Symfony versions
=> update Travis CI configuration

.travis.yml, composer.json
=> Allow Symfony 3 to be installed

Resources/config/schema/monolog-1.0.xsd
reflects changes from #108, 2555f140938de6d2a2b9e428cf46e8f98ca4dbd9 and #145
=> update XSD file with ElasticSearch handler options

CHANGELOG.md
Those changes are in v3, not v2.
=> Fix changelog version info

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, composer.json
Hello,
With the new version of Monolog, we have two new handler SlackWebhookHandler and SlackbotHandler 
https://github.com/Seldaek/monolog/pull/846
I purpose this PR for add it into monolog-bundle configuration.
I wait for your reviews if you need.
Thanks
=> Add SlackWebhookHandler and SlackbotHandler into configuration

DependencyInjection/MonologExtension.php, Resources/config/monolog.xml
Fixes https://github.com/symfony/symfony/pull/21517#issuecomment-277216071
=> Add autowiring alias for LoggerInterface

DependencyInjection/Compiler/LoggerChannelPass.php
=> use ChildDefinition if available

CHANGELOG.md, DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Resources/doc/index.rst, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/Fixtures/xml/server_log.xml, Tests/DependencyInjection/Fixtures/yml/server_log.yml
Support for https://github.com/symfony/symfony/pull/21080
=> Added support for ServerLog command

composer.json
Same as https://github.com/symfony/symfony/pull/16397
=> Add exclude-from-classmap for autoloading

DependencyInjection/MonologExtension.php
Following @Tobion's comment https://github.com/symfony/symfony/issues/25958#issuecomment-363462107, I've made an attempt to eliminate all randomly generated service IDs from `MonologExtension`.
`MonologExtension` currently uses `uniqid` to generate a service ID to be used in a single reference afterwards. I'm now directly inlining the affected definitions, so there is not need for randomly generated service IDs anymore.
=> Remove randomness from container compilation

DependencyInjection/MonologExtension.php
=> Remove Extra spaces

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Resources/config/schema/monolog-1.0.xsd, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/MonologExtensionTest.php
This PR adds the $useLocking StreamHandler argument : https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/StreamHandler.php#L44
=> Add stream handler lock option

CHANGELOG.md, DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Resources/config/schema/monolog-1.0.xsd
=> add InsightOps support

DependencyInjection/MonologExtension.php, Resources/config/monolog.xml
fixes:
* https://github.com/symfony/symfony/pull/34423
* https://github.com/symfony/symfony/pull/32360#issuecomment-554511075
* https://github.com/symfony/symfony-docs/pull/12642
=> Use an HttpClient without logger in all handlers

CHANGELOG.md, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/MonologExtensionTest.php
This PR is yet another attempt at solving issue #220, just like #245 and #289 before.
Sorry, for opening yet another PR for this, but since there wasn't much activity I figured I give it a go.
=> Set log level from parameter or envvar.

.travis.yml, CHANGELOG.md, DependencyInjection/MonologExtension.php, MonologBundle.php, composer.json
=> Drop support Symfony 3.4

CHANGELOG.md, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php, Tests/DependencyInjection/MonologExtensionTest.php
=> Use `ActivationStrategy` instead of `actionLevel` when available

DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/FixtureMonologExtensionTest.php
=> Use "use_locking" option with rotating file handler as well

CHANGELOG.md, DependencyInjection/Configuration.php, DependencyInjection/MonologExtension.php
Reverts symfony/monolog-bundle#364
=> Revert "Add Datadog monolog integration"

DependencyInjection/Configuration.php
Add user, password and transport for elasticsearch configuration example.
=> elasticsearch configuration example

CHANGELOG.md
https://github.com/symfony/monolog-bundle/compare/v3.7.0...46d8af4e23698db45649e90279cf1a99c0c6cd2b
=> Release 3.7.1

DependencyInjection/MonologExtension.php
Change 'MongoClient'  Definition to 'MongoDB\Client' - Fixes #420
=> Change 'MongoClient'  Definition to 'MongoDB\Client' - Fixes #420

DependencyInjection/Configuration.php
=> Fix potentials handlers added multiple times

DependencyInjection/MonologExtension.php, Tests/DependencyInjection/Fixtures/AsMonologProcessor/FooProcessor.php, Tests/DependencyInjection/Fixtures/AsMonologProcessor/RedeclareMethodProcessor.php, Tests/DependencyInjection/MonologExtensionTest.php
This feature allows configuring Monolog processors with an attribute. I basically copied `AsEventListener`.
=> Leverage AsMonologProcessor attribute

.gitattributes
=> Ignore .github, .gitattributes, .gitignore from vendor
